import { Result, success, failure } from '../shared/Result';
import { OrganizationDomainCodes } from './OrganizationDomainCodes';

export const ORGANIZATION_NAME_MAX_LENGTH = 255;
export const ORGANIZATION_DESCRIPTION_MAX_LENGTH = 2000;

export interface OrganizationProps {
  id: string;
  name: string;
  description: string;
  parentId: string | null;
  createdById: string;
  createdAt: Date;
  archivedAt: Date | null;
  allowMultiTreeMembership: boolean | null;
}

export class Organization {
  private constructor(private props: OrganizationProps) {}

  public static create(
    name: string,
    description: string,
    createdById: string,
    parentId: string | null = null,
    allowMultiTreeMembership?: boolean
  ): Result<Organization, string> {
    // Validate name
    if (!name || name.trim().length === 0) {
      return failure(OrganizationDomainCodes.ORGANIZATION_NAME_EMPTY);
    }

    if (name.length > ORGANIZATION_NAME_MAX_LENGTH) {
      return failure(OrganizationDomainCodes.ORGANIZATION_NAME_TOO_LONG);
    }

    // Validate description
    if (!description || description.trim().length === 0) {
      return failure(OrganizationDomainCodes.ORGANIZATION_DESCRIPTION_EMPTY);
    }

    if (description.length > ORGANIZATION_DESCRIPTION_MAX_LENGTH) {
      return failure(OrganizationDomainCodes.ORGANIZATION_DESCRIPTION_TOO_LONG);
    }

    const organization = new Organization({
      id: '', // Will be generated by repository
      name: name.trim(),
      description: description.trim(),
      parentId,
      createdById,
      createdAt: new Date(),
      archivedAt: null,
      allowMultiTreeMembership: parentId
        ? null
        : (allowMultiTreeMembership ?? false),
    });

    return success(organization);
  }

  public static reconstitute(props: OrganizationProps): Organization {
    return new Organization(props);
  }

  // Getters
  public get id(): string {
    return this.props.id;
  }

  public get name(): string {
    return this.props.name;
  }

  public get description(): string {
    return this.props.description;
  }

  public get parentId(): string | null {
    return this.props.parentId;
  }

  public get createdById(): string {
    return this.props.createdById;
  }

  public get createdAt(): Date {
    return this.props.createdAt;
  }

  public get archivedAt(): Date | null {
    return this.props.archivedAt;
  }

  public get allowMultiTreeMembership(): boolean | null {
    return this.props.allowMultiTreeMembership;
  }

  public isArchived(): boolean {
    return this.props.archivedAt !== null;
  }

  public archive(): Result<void, string> {
    if (this.isArchived()) {
      return failure(OrganizationDomainCodes.ORGANIZATION_ALREADY_ARCHIVED);
    }

    this.props.archivedAt = new Date();

    return success(undefined);
  }

  public unarchive(): Result<void, string> {
    if (!this.isArchived()) {
      return failure(OrganizationDomainCodes.ORGANIZATION_NOT_ARCHIVED);
    }

    this.props.archivedAt = null;

    return success(undefined);
  }

  public updateName(name: string): Result<void, string> {
    if (!name || name.trim().length === 0) {
      return failure(OrganizationDomainCodes.ORGANIZATION_NAME_EMPTY);
    }

    if (name.length > ORGANIZATION_NAME_MAX_LENGTH) {
      return failure(OrganizationDomainCodes.ORGANIZATION_NAME_TOO_LONG);
    }

    this.props.name = name.trim();

    return success(undefined);
  }

  public updateDescription(description: string): Result<void, string> {
    if (!description || description.trim().length === 0) {
      return failure(OrganizationDomainCodes.ORGANIZATION_DESCRIPTION_EMPTY);
    }

    if (description.length > ORGANIZATION_DESCRIPTION_MAX_LENGTH) {
      return failure(OrganizationDomainCodes.ORGANIZATION_DESCRIPTION_TOO_LONG);
    }

    this.props.description = description.trim();

    return success(undefined);
  }

  public toJSON(): OrganizationProps {
    return {
      ...this.props,
    };
  }
}
