import { Result, success, failure } from '../shared/Result';
import { DomainErrors } from '../shared/DomainErrors';

export interface OrganizationProps {
  id: string;
  name: string;
  description: string;
  parentId: string | null;
  createdById: string;
  createdAt: Date;
  archivedAt: Date | null;
}

export class Organization {
  private constructor(private props: OrganizationProps) {}

  public static create(
    name: string,
    description: string,
    createdById: string,
    parentId: string | null = null
  ): Result<Organization, string> {
    // Validate name
    if (!name || name.trim().length === 0) {
      return failure(DomainErrors.ORGANIZATION_NAME_EMPTY);
    }

    if (name.length > 255) {
      return failure(DomainErrors.ORGANIZATION_NAME_TOO_LONG);
    }

    // Validate description
    if (!description || description.trim().length === 0) {
      return failure(DomainErrors.ORGANIZATION_DESCRIPTION_EMPTY);
    }

    if (description.length > 2000) {
      return failure(DomainErrors.ORGANIZATION_DESCRIPTION_TOO_LONG);
    }

    const organization = new Organization({
      id: '', // Will be generated by repository
      name: name.trim(),
      description: description.trim(),
      parentId,
      createdById,
      createdAt: new Date(),
      archivedAt: null,
    });

    return success(organization);
  }

  public static reconstitute(props: OrganizationProps): Organization {
    return new Organization(props);
  }

  // Getters
  public get id(): string {
    return this.props.id;
  }

  public get name(): string {
    return this.props.name;
  }

  public get description(): string {
    return this.props.description;
  }

  public get parentId(): string | null {
    return this.props.parentId;
  }

  public get createdById(): string {
    return this.props.createdById;
  }

  public get createdAt(): Date {
    return this.props.createdAt;
  }

  public get archivedAt(): Date | null {
    return this.props.archivedAt;
  }

  public isArchived(): boolean {
    return this.props.archivedAt !== null;
  }

  public archive(): Result<void, string> {
    if (this.isArchived()) {
      return failure(DomainErrors.ORGANIZATION_ALREADY_ARCHIVED);
    }

    this.props.archivedAt = new Date();

    return success(undefined);
  }

  public setId(id: string): void {
    this.props.id = id;
  }

  public toJSON(): OrganizationProps {
    return {
      ...this.props,
    };
  }
}
