// Read-only demo-summary script.
//
// Prints the cross-tree demo scenario's ownership + expected voting weights
// from the LIVE database state — no destructive reset, no re-seeding.
// Run:   yarn db:demo-summary
//
// The same printer is used by `prisma/seed.ts` after it inserts the demo
// data, so the table you see during seeding and the one you see from this
// script are generated by the same code path.

import 'dotenv/config';
import { PrismaClient } from '../generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import { computeWeights } from '../src/domain/poll/WeightDistribution';
import { DistributionType } from '../src/domain/poll/DistributionType';
import { PropertyAggregation } from '../src/domain/poll/PropertyAggregation';

export interface CrossTreeSummaryData {
  orgs: {
    a: { id: string; name: string };
    b: { id: string; name: string };
    c: { id: string; name: string };
  };
  userNameById: Map<string, string>;
  memberships: Array<{ userId: string; orgId: string }>;
  // Flat list of active ownership rows with the info needed to pretty-print.
  ownerships: Array<{
    userId: string;
    assetId: string;
    assetName: string;
    size: number;
    propertyId: string;
    share: number;
  }>;
  // The two properties (for per-property normalization denominators).
  aptProperty: {
    id: string;
    name: string;
    assets: Array<{ id: string; size: number }>;
  };
  parkingProperty: {
    id: string;
    name: string;
    assets: Array<{ id: string; size: number }>;
  };
}

export async function loadCrossTreeData(
  client: PrismaClient
): Promise<CrossTreeSummaryData | null> {
  const orgA = await client.organization.findFirst({
    where: { name: 'Tree Root A (demo)' },
  });

  if (!orgA) {
    return null;
  }

  const children = await client.organization.findMany({
    where: { parentId: orgA.id },
    orderBy: { createdAt: 'asc' },
  });
  const orgB = children.find((c) => c.name === 'Building B (demo)');
  const orgC = children.find((c) => c.name === 'Parking C (demo)');

  if (!orgB || !orgC) {
    return null;
  }

  const allOrgIds = [orgA.id, orgB.id, orgC.id];

  const memberRows = await client.organizationUser.findMany({
    where: { organizationId: { in: allOrgIds }, status: 'accepted' },
    include: {
      user: { select: { id: true, firstName: true } },
    },
  });
  const userNameById = new Map<string, string>();

  for (const m of memberRows) {
    userNameById.set(m.userId, m.user.firstName);
  }

  const memberships = memberRows.map((m) => ({
    userId: m.userId,
    orgId: m.organizationId,
  }));

  // Match production snapshot semantics: skip archived properties and assets.
  // An archived asset can still have an active ownership row (SCD-2 history is
  // never end-dated by archiving) — including those would silently double-count
  // in the demo summary while the real poll snapshot quietly omits them.
  const properties = await client.organizationProperty.findMany({
    where: { organizationId: { in: allOrgIds }, archivedAt: null },
    include: {
      assets: {
        where: { archivedAt: null },
        orderBy: { createdAt: 'asc' },
      },
    },
    orderBy: { createdAt: 'asc' },
  });
  const apt = properties.find((p) => p.organizationId === orgB.id);
  const parking = properties.find((p) => p.organizationId === orgC.id);

  if (!apt || !parking) {
    return null;
  }

  const ownershipRows = await client.propertyAssetOwnership.findMany({
    where: {
      effectiveUntil: null,
      userId: { not: null }, // only user-backed rows (no external-owner placeholders)
      asset: {
        archivedAt: null,
        property: {
          archivedAt: null,
          organizationId: { in: allOrgIds },
        },
      },
    },
    include: {
      asset: {
        select: { id: true, name: true, size: true, propertyId: true },
      },
    },
    orderBy: [{ asset: { createdAt: 'asc' } }, { createdAt: 'asc' }],
  });

  return {
    orgs: {
      a: { id: orgA.id, name: 'Tree Root A' },
      b: { id: orgB.id, name: 'Building B' },
      c: { id: orgC.id, name: 'Parking C' },
    },
    userNameById,
    memberships,
    ownerships: ownershipRows.map((r) => ({
      userId: r.userId!,
      assetId: r.assetId,
      assetName: r.asset.name,
      size: Number(r.asset.size),
      propertyId: r.asset.propertyId,
      share: Number(r.share),
    })),
    aptProperty: {
      id: apt.id,
      name: apt.name,
      assets: apt.assets.map((a) => ({ id: a.id, size: Number(a.size) })),
    },
    parkingProperty: {
      id: parking.id,
      name: parking.name,
      assets: parking.assets.map((a) => ({ id: a.id, size: Number(a.size) })),
    },
  };
}

export function printCrossTreeSummary(data: CrossTreeSummaryData): void {
  const {
    orgs,
    userNameById,
    memberships,
    ownerships,
    aptProperty,
    parkingProperty,
  } = data;

  console.log('\n=== Cross-Tree Ownership Demo ===');
  console.log(
    `Tree:  ${orgs.a.name} (root) → [${orgs.b.name}, ${orgs.c.name}]`
  );

  // Memberships: userId → orgs[]
  const orgLabel = new Map<string, string>([
    [orgs.a.id, orgs.a.name],
    [orgs.b.id, orgs.b.name],
    [orgs.c.id, orgs.c.name],
  ]);
  const userOrgs = new Map<string, string[]>();

  for (const m of memberships) {
    const labels = userOrgs.get(m.userId) ?? [];
    labels.push(orgLabel.get(m.orgId)!);
    userOrgs.set(m.userId, labels);
  }

  console.log('Memberships:');

  for (const [userId, name] of userNameById) {
    const orgsList = (userOrgs.get(userId) ?? []).join(', ');
    const multi =
      (userOrgs.get(userId)?.length ?? 0) > 1 ? '   (multi-tree)' : '';
    console.log(`  ${name.padEnd(6)} → ${orgsList}${multi}`);
  }

  // Ownership
  console.log('\nOwnership:');

  for (const o of ownerships) {
    const owner = userNameById.get(o.userId) ?? o.userId;
    const pct = (o.share * 100).toFixed(0);
    console.log(
      `  ${owner.padEnd(6)} owns ${pct.padStart(3)}% of ${o.assetName.padEnd(10)} (${o.size} m²)`
    );
  }

  // Build the input shape for computeWeights.
  const allAssets = [
    ...aptProperty.assets.map((a) => ({
      id: a.id,
      propertyId: aptProperty.id,
      size: a.size,
    })),
    ...parkingProperty.assets.map((a) => ({
      id: a.id,
      propertyId: parkingProperty.id,
      size: a.size,
    })),
  ];
  const allOwnerships = ownerships.map((o) => ({
    assetId: o.assetId,
    userId: o.userId,
    share: o.share,
  }));

  // Candidate sets per scenario (simulates org-tree membership dedup).
  const candidatesTree = Array.from(userNameById.keys()); // A + descendants
  const candidatesB = memberships
    .filter((m) => m.orgId === orgs.b.id)
    .map((m) => m.userId);
  const candidatesC = memberships
    .filter((m) => m.orgId === orgs.c.id)
    .map((m) => m.userId);

  interface Scenario {
    label: string;
    candidates: string[];
    distributionType: DistributionType;
    propertyAggregation: PropertyAggregation;
    propertyIds: string[];
    // Poll's organization tree — for direct-org polls we narrow the asset set.
    orgTree: 'all' | 'b-only' | 'c-only';
  }

  // Mirror the strings the UI shows in the weight-distribution dropdown
  // (messages.poll.distribution.types.* and messages.poll.aggregation.*) so
  // CLI output is comparable side-by-side with the participants page.
  const distLabel: Record<DistributionType, string> = {
    [DistributionType.EQUAL]: 'Equal (1 per participant)',
    [DistributionType.OWNERSHIP_UNIT_COUNT]: 'By unit count',
    [DistributionType.OWNERSHIP_SIZE_WEIGHTED]: 'By unit size',
  };
  const aggLabel: Record<PropertyAggregation, string> = {
    [PropertyAggregation.RAW_SUM]: 'Raw sum',
    [PropertyAggregation.NORMALIZE_PER_PROPERTY]: 'Normalize per property',
  };

  const scenarios: Scenario[] = [
    {
      label: 'Poll @ A, no scope (all tree members vote)',
      candidates: candidatesTree,
      distributionType: DistributionType.EQUAL,
      propertyAggregation: PropertyAggregation.RAW_SUM,
      propertyIds: [],
      orgTree: 'all',
    },
    {
      label: 'Poll @ A, all tree properties',
      candidates: candidatesTree,
      distributionType: DistributionType.OWNERSHIP_SIZE_WEIGHTED,
      propertyAggregation: PropertyAggregation.RAW_SUM,
      propertyIds: [],
      orgTree: 'all',
    },
    {
      label: 'Poll @ A, all tree properties',
      candidates: candidatesTree,
      distributionType: DistributionType.OWNERSHIP_SIZE_WEIGHTED,
      propertyAggregation: PropertyAggregation.NORMALIZE_PER_PROPERTY,
      propertyIds: [],
      orgTree: 'all',
    },
    {
      label: 'Poll @ A, all tree properties',
      candidates: candidatesTree,
      distributionType: DistributionType.OWNERSHIP_UNIT_COUNT,
      propertyAggregation: PropertyAggregation.RAW_SUM,
      propertyIds: [],
      orgTree: 'all',
    },
    {
      label: 'Poll @ A, all tree properties',
      candidates: candidatesTree,
      distributionType: DistributionType.OWNERSHIP_UNIT_COUNT,
      propertyAggregation: PropertyAggregation.NORMALIZE_PER_PROPERTY,
      propertyIds: [],
      orgTree: 'all',
    },
    {
      label: 'Poll @ B (direct org only)',
      candidates: candidatesB,
      distributionType: DistributionType.OWNERSHIP_SIZE_WEIGHTED,
      propertyAggregation: PropertyAggregation.RAW_SUM,
      propertyIds: [],
      orgTree: 'b-only',
    },
    {
      label: 'Poll @ C (direct org only)',
      candidates: candidatesC,
      distributionType: DistributionType.OWNERSHIP_UNIT_COUNT,
      propertyAggregation: PropertyAggregation.NORMALIZE_PER_PROPERTY,
      propertyIds: [],
      orgTree: 'c-only',
    },
  ];

  console.log(
    '\nExpected weights (computed via WeightDistribution.computeWeights):'
  );

  for (const s of scenarios) {
    // Direct-org polls only see their org's assets/ownerships.
    let scopedAssets = allAssets;
    let scopedOwnerships = allOwnerships;

    if (s.orgTree === 'b-only') {
      scopedAssets = allAssets.filter((a) => a.propertyId === aptProperty.id);
      scopedOwnerships = allOwnerships.filter((o) =>
        scopedAssets.some((a) => a.id === o.assetId)
      );
    } else if (s.orgTree === 'c-only') {
      scopedAssets = allAssets.filter(
        (a) => a.propertyId === parkingProperty.id
      );
      scopedOwnerships = allOwnerships.filter((o) =>
        scopedAssets.some((a) => a.id === o.assetId)
      );
    }

    const weights = computeWeights({
      candidates: s.candidates,
      distributionType: s.distributionType,
      propertyAggregation: s.propertyAggregation,
      propertyIds: s.propertyIds,
      assets: scopedAssets,
      ownerships: scopedOwnerships,
    });

    // Show both the enum (what code/tests reference) and the UI label (what
    // the user sees in the dropdown) so the CLI is comparable side-by-side
    // with the participants page. Aggregation only printed for ownership
    // modes — EQUAL ignores it.
    const distPart = `${s.distributionType} (${distLabel[s.distributionType]})`;
    const aggPart =
      s.distributionType === DistributionType.EQUAL
        ? ''
        : `, ${s.propertyAggregation} (${aggLabel[s.propertyAggregation]})`;
    console.log(`\n  • ${s.label} — ${distPart}${aggPart}`);

    for (const uid of s.candidates) {
      const name = userNameById.get(uid) ?? uid;
      const w = weights.get(uid);
      const display = w === undefined ? '— (no weight)' : w.toFixed(4);
      console.log(`      ${name.padEnd(6)} → ${display}`);
    }
  }

  console.log('\n  (Weight mechanics: co-owners split the asset contribution;');
  console.log('   RAW_SUM mixes units — larger properties dominate;');
  console.log(
    '   NORMALIZE_PER_PROPERTY makes every property contribute ≤ 1.0 before summing.)'
  );
  console.log('\nDemo credentials: password = "password123"');
  console.log('  Alice: +79162000001   Bob:   +79162000002');
  console.log(
    '  Helen: +79162000003   Oscar: +79162000004 (multi-tree member)'
  );
}

// CLI entry — only runs when this file is invoked directly.
async function main() {
  const { Pool } = pg;
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter });

  try {
    const data = await loadCrossTreeData(prisma);

    if (!data) {
      console.log(
        'Cross-tree demo scenario not found in database.\n' +
          'Run `yarn db:seed` first to create it.'
      );
      process.exit(0);
    }

    printCrossTreeSummary(data);
  } finally {
    await prisma.$disconnect();
    await pool.end();
  }
}

// Detect direct invocation: `npx tsx prisma/demo-summary.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error('demo-summary error:', e);
    process.exit(1);
  });
}
