import { PhoneNumber } from './PhoneNumber';
import {
  Locale,
  defaultLocale,
  isValidLocale,
  locales,
} from '../../i18n/locales';

export type Language = Locale;

export interface UserProps {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  phoneNumber: PhoneNumber;
  password: string;
  language: Language;
  createdAt: Date;
}

export class User {
  private constructor(private readonly props: UserProps) {}

  static create(
    props: Omit<UserProps, 'id' | 'createdAt' | 'language'> & {
      language?: Language;
    }
  ): User {
    // Validate required fields
    if (!props.firstName?.trim()) {
      throw new Error('First name is required');
    }
    if (!props.lastName?.trim()) {
      throw new Error('Last name is required');
    }
    if (!props.password?.trim()) {
      throw new Error('Password is required');
    }

    // Set default language if not provided (Russian is default per routing config)
    const language = props.language || defaultLocale;

    // Validate language
    if (!isValidLocale(language)) {
      throw new Error(`Language must be one of: ${locales.join(', ')}`);
    }

    return new User({
      ...props,
      language,
      id: '', // Will be generated by infrastructure layer
      createdAt: new Date(),
    });
  }

  static reconstitute(props: UserProps): User {
    return new User(props);
  }

  get id(): string {
    return this.props.id;
  }

  get firstName(): string {
    return this.props.firstName;
  }

  get lastName(): string {
    return this.props.lastName;
  }

  get middleName(): string | undefined {
    return this.props.middleName;
  }

  get phoneNumber(): PhoneNumber {
    return this.props.phoneNumber;
  }

  get password(): string {
    return this.props.password;
  }

  get language(): Language {
    return this.props.language;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  getFullName(): string {
    return this.middleName
      ? `${this.firstName} ${this.middleName} ${this.lastName}`
      : `${this.firstName} ${this.lastName}`;
  }

  // Method to check if user can be authenticated
  canAuthenticate(): boolean {
    return !!this.password && !!this.phoneNumber;
  }

  // Update methods - return new instances to maintain immutability
  updateLanguage(language: string): User {
    if (!isValidLocale(language)) {
      throw new Error(`Language must be one of: ${locales.join(', ')}`);
    }

    return new User({
      ...this.props,
      language: language as Language,
    });
  }

  updateMiddleName(middleName: string | undefined): User {
    return new User({
      ...this.props,
      middleName,
    });
  }
}
