import { PhoneNumber } from './PhoneNumber';
import { Nickname } from './Nickname';
import { Address } from './Address';
import { UserDomainCodes } from './UserDomainCodes';
import { SharedDomainCodes } from '../shared/SharedDomainCodes';
import { ProfanityChecker } from '../shared/profanity/ProfanityChecker';
import {
  Locale,
  defaultLocale,
  isValidLocale,
  locales,
} from '../../i18n/locales';

export type Language = Locale;

export const PASSWORD_MIN_LENGTH = 8;
export const NAME_MIN_LENGTH = 2;
export const NAME_MAX_LENGTH = 50;
export const NAME_REGEX = /^[A-ZА-ЯЁ][a-zA-Zа-яёА-ЯЁ'\u2019\-]+$/;

export interface UserProps {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  phoneNumber: PhoneNumber;
  password: string;
  language: Language;
  createdAt: Date;
  consentGivenAt?: Date;
  nickname: Nickname;
  allowFindByName: boolean;
  allowFindByPhone: boolean;
  allowFindByAddress: boolean;
  address?: Address;
  privacySetupCompleted: boolean;
  confirmedAt?: Date;
}

export interface PersonalInfoForPasswordCheck {
  firstName?: string;
  lastName?: string;
  middleName?: string;
  phoneNumber?: string;
}

export function passwordMatchesPersonalInfo(
  password: string,
  info: PersonalInfoForPasswordCheck
): boolean {
  if (!password) {
    return false;
  }

  const lower = password.toLowerCase();
  const names = [info.firstName, info.lastName, info.middleName].filter(
    (n): n is string => !!n && n.trim().length > 0
  );

  for (const name of names) {
    if (lower === name.toLowerCase()) {
      return true;
    }
  }

  // Fuzzy phone match: users often copy-paste the phone number as password,
  // sometimes losing the "+" prefix. Reject if ≥90% of the phone's digits
  // appear as a consecutive substring in the password.
  // E.g. for "+79161234567" (11 digits), threshold = ceil(11*0.9) = 10,
  // so "7916123456" (10 consecutive digits) is rejected, "791612345" (9) is not.
  if (info.phoneNumber) {
    const phoneDigits = info.phoneNumber.replace(/\D/g, '');

    if (phoneDigits.length > 0) {
      const threshold = Math.ceil(phoneDigits.length * 0.9);

      // Check all consecutive substrings of length threshold..full
      for (let len = phoneDigits.length; len >= threshold; len--) {
        for (let start = 0; start <= phoneDigits.length - len; start++) {
          if (password.includes(phoneDigits.substring(start, start + len))) {
            return true;
          }
        }
      }
    }
  }

  return false;
}

export class User {
  private constructor(private readonly props: UserProps) {}

  static create(
    props: Omit<
      UserProps,
      | 'id'
      | 'createdAt'
      | 'language'
      | 'nickname'
      | 'allowFindByName'
      | 'allowFindByPhone'
      | 'allowFindByAddress'
      | 'address'
      | 'privacySetupCompleted'
    > & {
      language?: Language;
      consentGivenAt?: Date;
      nickname?: Nickname;
    },
    profanityChecker?: ProfanityChecker
  ): User {
    // Validate required fields
    if (!props.firstName?.trim()) {
      throw new Error('First name is required');
    }

    if (
      props.firstName.length > NAME_MAX_LENGTH ||
      !NAME_REGEX.test(props.firstName)
    ) {
      throw new Error(UserDomainCodes.FIRST_NAME_INVALID);
    }

    if (!props.lastName?.trim()) {
      throw new Error('Last name is required');
    }

    if (
      props.lastName.length > NAME_MAX_LENGTH ||
      !NAME_REGEX.test(props.lastName)
    ) {
      throw new Error(UserDomainCodes.LAST_NAME_INVALID);
    }

    if (
      props.middleName &&
      (props.middleName.length > NAME_MAX_LENGTH ||
        !NAME_REGEX.test(props.middleName))
    ) {
      throw new Error(UserDomainCodes.MIDDLE_NAME_INVALID);
    }

    if (profanityChecker?.containsProfanity(props.firstName)) {
      throw new Error(SharedDomainCodes.CONTAINS_PROFANITY);
    }

    if (profanityChecker?.containsProfanity(props.lastName)) {
      throw new Error(SharedDomainCodes.CONTAINS_PROFANITY);
    }

    if (
      props.middleName &&
      profanityChecker?.containsProfanity(props.middleName)
    ) {
      throw new Error(SharedDomainCodes.CONTAINS_PROFANITY);
    }

    if (!props.password?.trim()) {
      throw new Error('Password is required');
    }

    // Set default language if not provided (Russian is default per routing config)
    const language = props.language || defaultLocale;

    // Validate language
    if (!isValidLocale(language)) {
      throw new Error(`Language must be one of: ${locales.join(', ')}`);
    }

    return new User({
      ...props,
      language,
      nickname: props.nickname || Nickname.generate(),
      id: '', // Will be generated by infrastructure layer
      createdAt: new Date(),
      consentGivenAt: props.consentGivenAt,
      allowFindByName: false,
      allowFindByPhone: false,
      allowFindByAddress: false,
      privacySetupCompleted: false,
    });
  }

  static reconstitute(
    props: Omit<
      UserProps,
      | 'nickname'
      | 'allowFindByName'
      | 'allowFindByPhone'
      | 'allowFindByAddress'
      | 'address'
      | 'privacySetupCompleted'
    > &
      Partial<
        Pick<
          UserProps,
          | 'nickname'
          | 'allowFindByName'
          | 'allowFindByPhone'
          | 'allowFindByAddress'
          | 'address'
          | 'privacySetupCompleted'
        >
      >
  ): User {
    return new User({
      ...props,
      nickname: props.nickname || Nickname.generate(),
      allowFindByName: props.allowFindByName ?? false,
      allowFindByPhone: props.allowFindByPhone ?? false,
      allowFindByAddress: props.allowFindByAddress ?? false,
      address: props.address,
      privacySetupCompleted: props.privacySetupCompleted ?? false,
    });
  }

  get id(): string {
    return this.props.id;
  }

  get firstName(): string {
    return this.props.firstName;
  }

  get lastName(): string {
    return this.props.lastName;
  }

  get middleName(): string | undefined {
    return this.props.middleName;
  }

  get phoneNumber(): PhoneNumber {
    return this.props.phoneNumber;
  }

  get password(): string {
    return this.props.password;
  }

  get language(): Language {
    return this.props.language;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get consentGivenAt(): Date | undefined {
    return this.props.consentGivenAt;
  }

  get nickname(): Nickname {
    return this.props.nickname;
  }

  get allowFindByName(): boolean {
    return this.props.allowFindByName;
  }

  get allowFindByPhone(): boolean {
    return this.props.allowFindByPhone;
  }

  get allowFindByAddress(): boolean {
    return this.props.allowFindByAddress;
  }

  get address(): Address | undefined {
    return this.props.address;
  }

  get privacySetupCompleted(): boolean {
    return this.props.privacySetupCompleted;
  }

  get confirmedAt(): Date | undefined {
    return this.props.confirmedAt;
  }

  isConfirmed(): boolean {
    return this.props.confirmedAt !== undefined;
  }

  confirm(): User {
    return new User({
      ...this.props,
      confirmedAt: new Date(),
    });
  }

  getFullName(): string {
    return User.formatFullName(this.firstName, this.lastName, this.middleName);
  }

  /**
   * Format a full name in lastName firstName middleName order.
   * Usable without a User instance (e.g. from plain objects / DTOs).
   */
  static formatFullName(
    firstName: string,
    lastName: string,
    middleName?: string | null
  ): string {
    return [lastName, firstName, middleName].filter(Boolean).join(' ');
  }

  // Method to check if user can be authenticated
  canAuthenticate(): boolean {
    return !!this.password && !!this.phoneNumber;
  }

  // Update methods - return new instances to maintain immutability
  updateLanguage(language: string): User {
    if (!isValidLocale(language)) {
      throw new Error(`Language must be one of: ${locales.join(', ')}`);
    }

    return new User({
      ...this.props,
      language: language as Language,
    });
  }

  updateMiddleName(
    middleName: string | undefined,
    profanityChecker?: ProfanityChecker
  ): User {
    if (middleName && profanityChecker?.containsProfanity(middleName)) {
      throw new Error(SharedDomainCodes.CONTAINS_PROFANITY);
    }

    return new User({
      ...this.props,
      middleName,
    });
  }

  updatePrivacySettings(settings: {
    allowFindByName?: boolean;
    allowFindByPhone?: boolean;
    allowFindByAddress?: boolean;
  }): User {
    return new User({
      ...this.props,
      allowFindByName: settings.allowFindByName ?? this.props.allowFindByName,
      allowFindByPhone:
        settings.allowFindByPhone ?? this.props.allowFindByPhone,
      allowFindByAddress:
        settings.allowFindByAddress ?? this.props.allowFindByAddress,
    });
  }

  updateNickname(nickname: Nickname): User {
    return new User({
      ...this.props,
      nickname,
    });
  }

  updateAddress(address: Address | undefined): User {
    return new User({
      ...this.props,
      address,
    });
  }

  completePrivacySetup(): User {
    return new User({
      ...this.props,
      privacySetupCompleted: true,
    });
  }
}
