import { PhoneNumber } from './PhoneNumber';

export interface UserProps {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  phoneNumber: PhoneNumber;
  password: string;
  createdAt: Date;
}

export class User {
  private constructor(private readonly props: UserProps) {}

  static create(props: Omit<UserProps, 'id' | 'createdAt'>): User {
    // Validate required fields
    if (!props.firstName?.trim()) {
      throw new Error('First name is required');
    }
    if (!props.lastName?.trim()) {
      throw new Error('Last name is required');
    }
    if (!props.password?.trim()) {
      throw new Error('Password is required');
    }

    return new User({
      ...props,
      id: '', // Will be generated by infrastructure layer
      createdAt: new Date(),
    });
  }

  static reconstitute(props: UserProps): User {
    return new User(props);
  }

  get id(): string {
    return this.props.id;
  }

  get firstName(): string {
    return this.props.firstName;
  }

  get lastName(): string {
    return this.props.lastName;
  }

  get middleName(): string | undefined {
    return this.props.middleName;
  }

  get phoneNumber(): PhoneNumber {
    return this.props.phoneNumber;
  }

  get password(): string {
    return this.props.password;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  getFullName(): string {
    return this.middleName
      ? `${this.firstName} ${this.middleName} ${this.lastName}`
      : `${this.firstName} ${this.lastName}`;
  }

  // Method to check if user can be authenticated
  canAuthenticate(): boolean {
    return !!this.password && !!this.phoneNumber;
  }
}
