// Common Russian derived forms missing from leo-profanity's dictionary.
// The library already covers: хуй/хуе/хуё, бля/блядь, еба/ебать, пизд, сук, долбоёб.
// е-variants of ё-forms (хуево, ебнуть, долбоеб, etc.) are auto-generated
// in LeoProfanityChecker constructor — no need to list them here.
// Most Russian morphology is handled by PROFANITY_STEMS (stem matching).
// This list only contains words NOT covered by stems or the library.
export const PROFANITY_CUSTOM_BLOCKED: string[] = [
  'хер', // standalone; can't use as stem (would catch херсон, херувим, херес)
  'манда', // standalone; can't use as stem (would catch мандарин, мандат)
  'манды',
  'манде',
  'манду',
  'мандой',
  'монда',
  'монды',
  'монде',
  'монду',
  'мондой',
];

// Profane stems for Russian morphology matching.
// Any word starting with one of these stems is considered profane.
// This catches all declensions/conjugations without enumerating every form.
// Stems are chosen to be long enough to avoid false positives on legitimate words.
export const PROFANITY_STEMS: string[] = [
  // хуй derivatives — stems for words starting with хуй/хуё
  'хуёв', // хуёвый, хуёвая...

  // NOTE: хуй/хуе/хуи moved to PROFANITY_INFIXES — they're safe as substrings
  // and need to catch prefixed forms (аааахуеть, нахуярить, etc.)

  // хер derivatives (standalone 'хер' is in CUSTOM_BLOCKED — too short for stem)
  'херов', // херово, херовый, херовая, херовой, херовому...
  'херн', // херня, херни, херне, херню, херней...
  'херосос', // херосос, херососка...
  'херасос', // херасос, херасоска...

  // мудак
  'мудак', // мудак, мудака, мудаком, мудаки, мудаков...
  'мудач', // мудачье, мудачок...
  'мудил', // мудила, мудило...

  // гандон/гондон
  'гандон', // гандон, гандона, гандоном, гандонка...
  'гондон', // гондон, гондона, гондоном, гондонка...

  // шлюх
  'шлюх', // шлюха, шлюхи, шлюхой, шлюхам...

  // пидор/пидар/пидер/пидир + педор/педар/педер/педир (all misspellings)
  'пидор', // пидор, пидора, пидором, пидорас, пидорами...
  'пидар', // пидар, пидара, пидары...
  'пидер', // пидераст...
  'пидир', // пидираст...
  'педор', // педорас, педораст...
  'педар', // педарас, педараст...
  'педер', // педераст...
  'педир', // педираст...

  // жоп
  'жоп', // жопа, жопы, жопе, жопу, жопой, жопам...

  // говн
  'говн', // говно, говна, говном, говнюк, говнище, говняный...

  // дроч
  'дроч', // дрочить, дрочит, дрочила, дрочу...

  // срат/срак/сран
  'срат', // срать, срал, срала, срали...
  'срак', // срака, сраки, сраку, сракой...
  'сран', // срань

  // залуп/золуп
  'залуп', // залупа, залупы, залупу, залупой...
  'золуп', // золупа, золупы, золупу...

  // минет/миньет/миннет
  'минет', // минет, минета, минету, минетом...
  'миньет', // миньет, миньета...
  'миннет', // миннет, миннета...

  // членосос
  'членосос', // членосос, членососка...

  // манда/монда (can't use 'манд' or 'манда' — would flag мандарин, мандат)
  'мандав', // мандавошка...
  'мандов', // мандовошка...
  'мандол', // мандолиз...
  'мондав', // мондавошка...
  'мондов', // мондовошка...
  'мондал', // мондализ...

  // епт/ёпт
  'епт', // епт
  'ёпт', // ёпт

  // пизд- (stem for words starting with пизд)
  'пизд', // пизда, пиздец, пиздас, пиздос, пиздолиз, пиздалис...

  // пезд- (misspelling of пизд-)
  'пезд', // пезда, пездализ, пездолиз, пездолис, пездалис...

  // еб- prefixed/derived (ебан, уебан, ебобо)
  'ебан', // ебан, ебаный, ебанат...
  'уебан', // уебан, уебаны...
  'ебоб', // ебобо...

  // долбое/далбое (е-variant and misspelling of долбоёб)
  'долбое', // долбоеб (also auto-generated from ё, but stem catches долбое*)
  'далбое', // далбоеб (misspelling)
  'далбоё', // далбоёб (misspelling with ё)

  // *еб compound words (animal + еб)
  'овцееб', // овцоёб written with е
  'авцееб', // misspelling
  'авциеб', // misspelling
  'ослоеб', // ослоёб written with е
  'аслоеб', // misspelling
  'аслаеб', // misspelling
  'козлоеб', // козлоёб written with е
  'козлаеб', // misspelling
  'казлоеб', // misspelling
  'казлаеб', // misspelling
  'овцеёб', // with ё
  'ослоёб', // with ё
  'козлоёб', // with ё
  'козлаёб', // misspelling with ё
  'казлоёб', // misspelling with ё
  'казлаёб', // misspelling with ё
];

// Profane infixes — checked as substrings within words.
// Catches all prefixed forms (до-, на-, за-, от-, рас-, рос-, при-, по-, ис-, в-).
// Only roots that don't appear as substrings in legitimate Russian words.
export const PROFANITY_INFIXES: string[] = [
  // хуй/хуе/хуи — safe as substrings, catches all prefixed forms
  'хуй', // нахуй, хуйня, хуйсгоры, нахуярить...
  'хуе', // хуеть, аааахуеть, хуевый, охуеть, хуеплет, хуесос...
  'хуи', // хуиверт, охуительный, ахуительный...
  'хуё', // хуёво, охуённый...

  'пизд', // допиздел, напиздел, отпиздил, распиздяй, роспиздня...
  'пезд', // misspelling variant
  'ебан', // уебан, заебаный...
  'ибан', // ибануть, ибанутый (misspelling of ебан)...
  'ибал', // разъибал, абъибал (misspelling of ебал)...
  'ебат', // заебать, проебать, наебать, доебать...
  'ебал', // заебал, проебал, наебал, доебал...
  'ебаш', // заебашить, наебашить...
  'ебас', // ебасить...
  'ебос', // ебос...
  'ёбну', // ёбнуть — and prefixed: долбоёбнуть...
  'ебну', // ебнуть (е-variant)
  'ебон', // ебонуть, ебонутый, ебонутая...
  'выеб', // выебу, выебать, вротвыебу...
];

// False positives to allow
export const PROFANITY_WHITELISTED: string[] = [];
