// Common Russian derived forms missing from leo-profanity's dictionary.
// The library already covers: хуй/хуе/хуё, бля/блядь, еба/ебать, пизд, сук, долбоёб.
// е-variants of ё-forms (хуево, ебнуть, долбоеб, etc.) are auto-generated
// in LeoProfanityChecker constructor — no need to list them here.
// Most Russian morphology is handled by PROFANITY_STEMS (stem matching).
// This list only contains words NOT covered by stems or the library.
export const PROFANITY_CUSTOM_BLOCKED: string[] = [];

// Profane stems for Russian morphology matching.
// Any word starting with one of these stems is considered profane.
// This catches all declensions/conjugations without enumerating every form.
// Stems are chosen to be long enough to avoid false positives on legitimate words.
export const PROFANITY_STEMS: string[] = [
  // хуй derivatives (adjectives, compounds, prefixed)
  'хуев', // хуевый, хуевая, хуевого, хуевому, хуевым, хуевых...
  'хуёв', // хуёвый, хуёвая...
  'хуеплет', // хуеплет, хуеплета...
  'хуесос', // хуесос, хуесоска, хуесосов...
  'охуе', // охуеть, охуенный, охуенная, охуенного...
  'охуи', // охуительный, охуительная...
  'ахуе', // ахуеть, ахуенный, ахуенная, ахуенного...
  'ахуи', // ахуительный...

  // мудак
  'мудак', // мудак, мудака, мудаком, мудаки, мудаков...
  'мудач', // мудачье, мудачок...
  'мудил', // мудила, мудило...

  // гандон/гондон
  'гандон', // гандон, гандона, гандоном, гандонка...
  'гондон', // гондон, гондона, гондоном, гондонка...

  // шлюх
  'шлюх', // шлюха, шлюхи, шлюхой, шлюхам...

  // пидор/пидар
  'пидор', // пидор, пидора, пидором, пидорас, пидорами...
  'пидар', // пидар, пидара, пидары...

  // жоп
  'жоп', // жопа, жопы, жопе, жопу, жопой, жопам...

  // говн
  'говн', // говно, говна, говном, говнюк, говнище, говняный...

  // хер
  'херов', // херово, херовый, херовая, херовой, херовому...
  'херн', // херня, херни, херне, херню, херней...

  // дроч
  'дроч', // дрочить, дрочит, дрочила, дрочу...

  // срат/срак/сран
  'срат', // срать, срал, срала, срали...
  'срак', // срака, сраки, сраку, сракой...
  'сран', // срань

  // залуп/золуп
  'залуп', // залупа, залупы, залупу, залупой...
  'золуп', // золупа, золупы, золупу...

  // минет/миньет/миннет
  'минет', // минет, минета, минету, минетом...
  'миньет', // миньет, миньета...
  'миннет', // миннет, миннета...

  // членосос
  'членосос', // членосос, членососка...

  // епт/ёпт
  'епт', // епт
  'ёпт', // ёпт
];

// False positives to allow
export const PROFANITY_WHITELISTED: string[] = [];
