import { Result, success, failure } from '../shared/Result';
import { DomainErrors } from '../shared/DomainErrors';

export interface BoardProps {
  id: string;
  name: string;
  organizationId: string;
  isGeneral: boolean;
  createdAt: Date;
  archivedAt: Date | null;
}

export class Board {
  private constructor(private props: BoardProps) {}

  public static create(
    name: string,
    organizationId: string,
    isGeneral: boolean = false
  ): Result<Board, string> {
    // Validate name
    if (!name || name.trim().length === 0) {
      return failure(DomainErrors.BOARD_NAME_EMPTY);
    }

    if (name.length > 255) {
      return failure(DomainErrors.BOARD_NAME_TOO_LONG);
    }

    const board = new Board({
      id: '', // Will be generated by repository
      name: name.trim(),
      organizationId,
      isGeneral,
      createdAt: new Date(),
      archivedAt: null,
    });

    return success(board);
  }

  public static reconstitute(props: BoardProps): Board {
    return new Board(props);
  }

  // Getters
  public get id(): string {
    return this.props.id;
  }

  public get name(): string {
    return this.props.name;
  }

  public get organizationId(): string {
    return this.props.organizationId;
  }

  public get isGeneral(): boolean {
    return this.props.isGeneral;
  }

  public get createdAt(): Date {
    return this.props.createdAt;
  }

  public get archivedAt(): Date | null {
    return this.props.archivedAt;
  }

  public isArchived(): boolean {
    return this.props.archivedAt !== null;
  }

  public archive(): Result<void, string> {
    if (this.isArchived()) {
      return failure(DomainErrors.BOARD_ALREADY_ARCHIVED);
    }

    this.props.archivedAt = new Date();

    return success(undefined);
  }

  public setId(id: string): void {
    this.props.id = id;
  }

  public toJSON(): BoardProps {
    return {
      ...this.props,
    };
  }
}
