name: Deploy to Beta

on:
  push:
    branches: [beta]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      branch: beta
      deploy_dir: /var/www/www-root/data/www/beta.resolutio.site
      site_url: https://beta.resolutio.site
      port: '3001'
